#pragma once

/* I2C for OLEDs */
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define TAPPING_TERM 200
// #define PERMISSIVE_HOLD
#define TAPPING_TERM_PER_KEY

#define OLED_TIMEOUT 30000

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
